# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        small:
            quality: 75
            filters:
                thumbnail: { size: [ 120, 120 ], mode: outbound }

        medium:
            quality: 75
            filters:
                thumbnail: { size: [ 200, 200 ], mode: outbound }

        product_card:
            quality: 75
            filters:
                relative_resize:
                    widen: 500

        brand_logo:
            quality: 75
            filters:
                relative_resize:
                    widen: 100


