<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SyiJH_VService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.syiJH.v' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.syiJH.v'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'productOptionRepository' => ['privates', 'App\\Repository\\ProductOptionRepository', 'getProductOptionRepositoryService', true],
        ], [
            'productOptionRepository' => 'App\\Repository\\ProductOptionRepository',
        ]);
    }
}
