<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GZx5DTTService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.gZx5DTT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gZx5DTT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'productOptionValueRepository' => ['privates', 'App\\Repository\\ProductOptionValueRepository', 'getProductOptionValueRepositoryService', true],
        ], [
            'productOptionValueRepository' => 'App\\Repository\\ProductOptionValueRepository',
        ]);
    }
}
