<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y9ayVwjService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.y9ayVwj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y9ayVwj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'feature' => ['privates', '.errored..service_locator.y9ayVwj.App\\Entity\\Feature', NULL, 'Cannot autowire service ".service_locator.y9ayVwj": it needs an instance of "App\\Entity\\Feature" but this type has been excluded in "config/services.yaml".'],
        ], [
            'feature' => 'App\\Entity\\Feature',
        ]);
    }
}
