<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DZksnopService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.dZksnop' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dZksnop'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'hero' => ['privates', '.errored..service_locator.dZksnop.App\\Entity\\Hero', NULL, 'Cannot autowire service ".service_locator.dZksnop": it needs an instance of "App\\Entity\\Hero" but this type has been excluded in "config/services.yaml".'],
        ], [
            'hero' => 'App\\Entity\\Hero',
        ]);
    }
}
