<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H17xdvWService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.H17xdvW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H17xdvW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'brand' => ['privates', '.errored..service_locator.H17xdvW.App\\Entity\\Brand', NULL, 'Cannot autowire service ".service_locator.H17xdvW": it needs an instance of "App\\Entity\\Brand" but this type has been excluded in "config/services.yaml".'],
            'imageRepository' => ['privates', 'App\\Repository\\ImageRepository', 'getImageRepositoryService', true],
        ], [
            'brand' => 'App\\Entity\\Brand',
            'imageRepository' => 'App\\Repository\\ImageRepository',
        ]);
    }
}
