<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OP_G4iZService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.OP.g4iZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OP.g4iZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'feature' => ['privates', '.errored..service_locator.OP.g4iZ.App\\Entity\\Feature', NULL, 'Cannot autowire service ".service_locator.OP.g4iZ": it needs an instance of "App\\Entity\\Feature" but this type has been excluded in "config/services.yaml".'],
            'imageRepository' => ['privates', 'App\\Repository\\ImageRepository', 'getImageRepositoryService', true],
        ], [
            'feature' => 'App\\Entity\\Feature',
            'imageRepository' => 'App\\Repository\\ImageRepository',
        ]);
    }
}
