<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SAlWKhXService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.SAlWKhX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SAlWKhX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'brand' => ['privates', '.errored..service_locator.SAlWKhX.App\\Entity\\Brand', NULL, 'Cannot autowire service ".service_locator.SAlWKhX": it needs an instance of "App\\Entity\\Brand" but this type has been excluded in "config/services.yaml".'],
        ], [
            'brand' => 'App\\Entity\\Brand',
        ]);
    }
}
