<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OrlZKZeService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.orlZKZe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.orlZKZe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'productOption' => ['privates', '.errored..service_locator.orlZKZe.App\\Entity\\ProductOption', NULL, 'Cannot autowire service ".service_locator.orlZKZe": it needs an instance of "App\\Entity\\ProductOption" but this type has been excluded in "config/services.yaml".'],
        ], [
            'productOption' => 'App\\Entity\\ProductOption',
        ]);
    }
}
