<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N9YkPLDService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.n9YkPLD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n9YkPLD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'productOptionValue' => ['privates', '.errored..service_locator.n9YkPLD.App\\Entity\\ProductOptionValue', NULL, 'Cannot autowire service ".service_locator.n9YkPLD": it needs an instance of "App\\Entity\\ProductOptionValue" but this type has been excluded in "config/services.yaml".'],
            'productOptionValueRepository' => ['privates', 'App\\Repository\\ProductOptionValueRepository', 'getProductOptionValueRepositoryService', true],
        ], [
            'productOptionValue' => 'App\\Entity\\ProductOptionValue',
            'productOptionValueRepository' => 'App\\Repository\\ProductOptionValueRepository',
        ]);
    }
}
