<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VZmeTnNService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.VZmeTnN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VZmeTnN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'default' => ['privates', 'html_sanitizer.sanitizer.default', 'getHtmlSanitizer_Sanitizer_DefaultService', true],
        ], [
            'default' => 'Symfony\\Component\\HtmlSanitizer\\HtmlSanitizer',
        ]);
    }
}
