<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QOBelzXService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.QOBelzX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QOBelzX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'discount' => ['privates', '.errored..service_locator.QOBelzX.App\\Entity\\Discount', NULL, 'Cannot autowire service ".service_locator.QOBelzX": it needs an instance of "App\\Entity\\Discount" but this type has been excluded in "config/services.yaml".'],
        ], [
            'discount' => 'App\\Entity\\Discount',
        ]);
    }
}
