<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ha9OD8dService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Ha9OD8d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ha9OD8d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'product' => ['privates', '.errored..service_locator.Ha9OD8d.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.Ha9OD8d": it needs an instance of "App\\Entity\\Product" but this type has been excluded in "config/services.yaml".'],
            'productVariantRepository' => ['privates', 'App\\Repository\\ProductVariantRepository', 'getProductVariantRepositoryService', true],
        ], [
            'product' => 'App\\Entity\\Product',
            'productVariantRepository' => 'App\\Repository\\ProductVariantRepository',
        ]);
    }
}
