<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBrandControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\BrandController' shared autowired service.
     *
     * @return \App\Controller\BrandController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\BrandController'] = $instance = new \App\Controller\BrandController(new \App\Service\BrandService(($container->privates['App\\Repository\\BrandRepository'] ?? $container->load('getBrandRepositoryService')), ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)), ($container->privates['Cocur\\Slugify\\Slugify'] ??= new \Cocur\Slugify\Slugify()), ($container->privates['validator'] ?? $container->load('getValidatorService'))));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\BrandController', $container));

        return $instance;
    }
}
