<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBrandEditTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\BrandEditType' shared autowired service.
     *
     * @return \App\Form\BrandEditType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\BrandEditType'] = new \App\Form\BrandEditType(($container->privates['App\\Repository\\ImageRepository'] ?? $container->load('getImageRepositoryService')));
    }
}
