<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDiscountService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.KnS9HUj.App\Entity\Discount' shared service.
     *
     * @return \App\Entity\Discount
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KnS9HUj": it needs an instance of "App\\Entity\\Discount" but this type has been excluded in "config/services.yaml".');
    }
}
