<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDiscountControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\DiscountController' shared autowired service.
     *
     * @return \App\Controller\DiscountController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\DiscountController'] = $instance = new \App\Controller\DiscountController(($container->privates['App\\Service\\DiscountService'] ?? $container->load('getDiscountServiceService')));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\DiscountController', $container));

        return $instance;
    }
}
