<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDiscountServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\DiscountService' shared autowired service.
     *
     * @return \App\Service\DiscountService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\DiscountService'] = new \App\Service\DiscountService(($container->privates['App\\Repository\\DiscountRepository'] ?? $container->load('getDiscountRepositoryService')));
    }
}
