<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeatureService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.OP.g4iZ.App\Entity\Feature' shared service.
     *
     * @return \App\Entity\Feature
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.OP.g4iZ": it needs an instance of "App\\Entity\\Feature" but this type has been excluded in "config/services.yaml".');
    }
}
