<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_TypeExtension_Form_HtmlSanitizerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'form.type_extension.form.html_sanitizer' shared service.
     *
     * @return \Symfony\Component\Form\Extension\HtmlSanitizer\Type\TextTypeHtmlSanitizerExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['form.type_extension.form.html_sanitizer'] = new \Symfony\Component\Form\Extension\HtmlSanitizer\Type\TextTypeHtmlSanitizerExtension(($container->privates['.service_locator.VZmeTnN'] ?? $container->load('get_ServiceLocator_VZmeTnNService')));
    }
}
