<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHeroTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\HeroType' shared autowired service.
     *
     * @return \App\Form\HeroType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\HeroType'] = new \App\Form\HeroType();
    }
}
