<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHeroControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\HeroController' shared autowired service.
     *
     * @return \App\Controller\HeroController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\HeroController'] = $instance = new \App\Controller\HeroController(new \App\Service\HeroService(($container->privates['App\\Repository\\HeroRepository'] ?? $container->load('getHeroRepositoryService')), ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\HeroController', $container));

        return $instance;
    }
}
