<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKernel_Listener_KernelRequestService extends App_KernelProdContainer
{
    /*
     * Gets the private 'kernel.listener.kernel_request' shared autowired service.
     *
     * @return \App\EventListener\NotFoundExceptionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['kernel.listener.kernel_request'] = new \App\EventListener\NotFoundExceptionListener(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['router'] ?? $container->getRouterService()));
    }
}
