<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductOptionValue2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.n9YkPLD.App\Entity\ProductOptionValue' shared service.
     *
     * @return \App\Entity\ProductOptionValue
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.n9YkPLD": it needs an instance of "App\\Entity\\ProductOptionValue" but this type has been excluded in "config/services.yaml".');
    }
}
