<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductOptionTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ProductOptionType' shared autowired service.
     *
     * @return \App\Form\ProductOptionType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ProductOptionType'] = new \App\Form\ProductOptionType();
    }
}
