<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ProductController' shared autowired service.
     *
     * @return \App\Controller\ProductController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ProductController'] = $instance = new \App\Controller\ProductController(new \App\Service\ProductService(($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)), ($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')), ($container->privates['App\\Repository\\ProductOptionRepository'] ?? $container->load('getProductOptionRepositoryService')), ($container->privates['App\\Repository\\ProductOptionValueRepository'] ?? $container->load('getProductOptionValueRepositoryService')), ($container->privates['App\\Repository\\ProductVariantOptionRepository'] ?? $container->load('getProductVariantOptionRepositoryService')), ($container->privates['App\\Repository\\ProductVariantRepository'] ?? $container->load('getProductVariantRepositoryService')), ($container->privates['Cocur\\Slugify\\Slugify'] ??= new \Cocur\Slugify\Slugify())));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\ProductController', $container));

        return $instance;
    }
}
