<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductOptionControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ProductOptionController' shared autowired service.
     *
     * @return \App\Controller\ProductOptionController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ProductOptionController'] = $instance = new \App\Controller\ProductOptionController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\ProductOptionController', $container));

        return $instance;
    }
}
