<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductOptionService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.0TeED.g.App\Entity\ProductOption' shared service.
     *
     * @return \App\Entity\ProductOption
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0TeED.g": it needs an instance of "App\\Entity\\ProductOption" but this type has been excluded in "config/services.yaml".');
    }
}
