<?php

namespace ContainerQnI309x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\UserService' shared autowired service.
     *
     * @return \App\Service\UserService
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['validator'] ?? $container->load('getValidatorService'));

        if (isset($container->privates['App\\Service\\UserService'])) {
            return $container->privates['App\\Service\\UserService'];
        }

        return $container->privates['App\\Service\\UserService'] = new \App\Service\UserService(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), $a);
    }
}
