<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.61b1725c.js',
                '/build/786.f9fdebac.js',
                '/build/app.3a772490.js',
            ],
            'css' => [
                '/build/app.9c094d9c.css',
            ],
        ],
    ],
],

]];
